name: New Bug Report
description: File a bug report here
title: '[BUG]: Title'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report
        Make sure there aren't any open/closed issues for this topic

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give us a brief description of what happened and what should have happened
    validations:
      required: true

  - type: textarea
    id: app-version
    attributes:
      label: Nora app Version
      description: Please provide detailed version information and installation method, such as v2.5.0-stable and Linux dmg file, Windows exe file, etc.
    placeholder: |
      version: v2.5.0-stable
      installation method: Windows exe file
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Run this command in your project's root folder and paste the result:

        ```sh
        npx envinfo --system --binaries --browsers
        ```
        add `| pbcopy` if you're in macOS for easy copy paste.
        Alternatively, you can manually gather the version information from your environment.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as logs, screenshots, scenarios in which the bug occurs so that it facilitates resolving the issue.

        Also attach the log file of the app to better understand what went wrong in the app.
        It is situated in C:\Users\USER_NAME\AppData\Roaming\nora\logs.txt

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
# This bug report is created with the help of Motrix's bug report (https://github.com/agalwood/Motrix/blob/master/.github/ISSUE_TEMPLATE/1_bug_report.yml)
